### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by jordanwillis** [scmoore68/teacozy#2]
Your CSS is also looking pretty good.  As I was viewing your page in the browser I noticed that no matter how I resized my browser, the page layout did not change and components did not automatically shrink/grow with the window.  It looks the reason there is no responsiveness in your layout is because of some fixed width styles in your stylesheet.

https://github.com/scmoore68/teacozy/blob/master/resources/css/style.css#L37
https://github.com/scmoore68/teacozy/blob/master/resources/css/style.css#L61
etc...

Unfortunately, using fixed width sizing like this eliminates the responsiveness of your layout because elements will not change size when the window is resized.  To achieve a responsive layout you will always want to stick with percent based widths instead.  Here is an example of what I mean for your header;

```
.header {
  width: 100%;
  /* the rest of your header styles */
}
```

By making this change throughout your code, the resulting page will shrink/grow nicely relative to the window.

**Comment by scmoore68** [comment]
This is good feedback, but we haven't officially learned the responsive layout concept yet since this project was for unit 4. I'm just now starting on unit 5 in the curriculum. So I'll know better next time how to create a page that adjusts for any size browser or device.
